# Define a versão do Docker Compose
version: '3.8'

services:
  
  # 1. O serviço da sua API
  api:
    build: .
    ports:
      - "8080:3000"
    environment:
      PORT: 3000
      # ATENÇÃO: Atualizamos a URL para usar o usuário 'root' e a senha
      # definida em MYSQL_ROOT_PASSWORD abaixo.
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    restart: unless-stopped

  # 2. O serviço do Banco de Dados (MySQL)
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

# Define os volumes que o Docker vai gerenciar
volumes:
  mysql-data: