version: '3.8'

services:
  
  api:
    build: .
    ports:
      - "8080:3000"
      - "5555:5555" 
    environment:
      PORT: 3000
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      DATABASE_URL: ${DATABASE_URL}
    
    command: npm run nodemon
    volumes:
      - .:/app
      - /app/node_modules
      - ./prisma:/app/prisma
    
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  mysql-data:
  redis-data: